//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KokaVeidsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KokaVeidsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCalculator.Resources.KokaVeidsResource", typeof(KokaVeidsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba.
        /// </summary>
        internal static string Ba {
            get {
                return ResourceManager.GetString("Ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be.
        /// </summary>
        internal static string Be {
            get {
                return ResourceManager.GetString("Be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bl.
        /// </summary>
        internal static string Bl {
            get {
                return ResourceManager.GetString("Bl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cp.
        /// </summary>
        internal static string Cp {
            get {
                return ResourceManager.GetString("Cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ds.
        /// </summary>
        internal static string Ds {
            get {
                return ResourceManager.GetString("Ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ķ.
        /// </summary>
        internal static string Ki {
            get {
                return ResourceManager.GetString("Ki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le.
        /// </summary>
        internal static string Le {
            get {
                return ResourceManager.GetString("Le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os.
        /// </summary>
        internal static string Os {
            get {
                return ResourceManager.GetString("Os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oz.
        /// </summary>
        internal static string Oz {
            get {
                return ResourceManager.GetString("Oz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        internal static string Pa {
            get {
                return ResourceManager.GetString("Pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sk.
        /// </summary>
        internal static string Sk {
            get {
                return ResourceManager.GetString("Sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vī.
        /// </summary>
        internal static string Vi {
            get {
                return ResourceManager.GetString("Vi", resourceCulture);
            }
        }
    }
}
