//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCalculator.Resources.MaatResource", typeof(MaatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am.
        /// </summary>
        internal static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap.
        /// </summary>
        internal static string Ap {
            get {
                return ResourceManager.GetString("Ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        internal static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av.
        /// </summary>
        internal static string Av {
            get {
                return ResourceManager.GetString("Av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db.
        /// </summary>
        internal static string Db {
            get {
                return ResourceManager.GetString("Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dm.
        /// </summary>
        internal static string Dm {
            get {
                return ResourceManager.GetString("Dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dms.
        /// </summary>
        internal static string Dms {
            get {
                return ResourceManager.GetString("Dms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DzivnBarLauces.
        /// </summary>
        internal static string DzivnBarLauces {
            get {
                return ResourceManager.GetString("DzivnBarLauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr.
        /// </summary>
        internal static string Gr {
            get {
                return ResourceManager.GetString("Gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grs.
        /// </summary>
        internal static string Grs {
            get {
                return ResourceManager.GetString("Grs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gs.
        /// </summary>
        internal static string Gs {
            get {
                return ResourceManager.GetString("Gs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KlajieSunuPurvi.
        /// </summary>
        internal static string KlajieSunuPurvi {
            get {
                return ResourceManager.GetString("KlajieSunuPurvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        internal static string Km {
            get {
                return ResourceManager.GetString("Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kp.
        /// </summary>
        internal static string Kp {
            get {
                return ResourceManager.GetString("Kp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krumaji.
        /// </summary>
        internal static string Krumaji {
            get {
                return ResourceManager.GetString("Krumaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ks.
        /// </summary>
        internal static string Ks {
            get {
                return ResourceManager.GetString("Ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kv.
        /// </summary>
        internal static string Kv {
            get {
                return ResourceManager.GetString("Kv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lk.
        /// </summary>
        internal static string Lk {
            get {
                return ResourceManager.GetString("Lk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        internal static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MezaNeapkl.
        /// </summary>
        internal static string MezaNeapkl {
            get {
                return ResourceManager.GetString("MezaNeapkl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nd.
        /// </summary>
        internal static string Nd {
            get {
                return ResourceManager.GetString("Nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeiezLauksaimn.
        /// </summary>
        internal static string NeiezLauksaimn {
            get {
                return ResourceManager.GetString("NeiezLauksaimn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NesaslEKult.
        /// </summary>
        internal static string NesaslEKult {
            get {
                return ResourceManager.GetString("NesaslEKult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NesaslPKult.
        /// </summary>
        internal static string NesaslPKult {
            get {
                return ResourceManager.GetString("NesaslPKult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pv.
        /// </summary>
        internal static string Pv {
            get {
                return ResourceManager.GetString("Pv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sl.
        /// </summary>
        internal static string Sl {
            get {
                return ResourceManager.GetString("Sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trases.
        /// </summary>
        internal static string Trases {
            get {
                return ResourceManager.GetString("Trases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virsaji.
        /// </summary>
        internal static string Virsaji {
            get {
                return ResourceManager.GetString("Virsaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vr.
        /// </summary>
        internal static string Vr {
            get {
                return ResourceManager.GetString("Vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrs.
        /// </summary>
        internal static string Vrs {
            get {
                return ResourceManager.GetString("Vrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZaluParejas.
        /// </summary>
        internal static string ZaluParejas {
            get {
                return ResourceManager.GetString("ZaluParejas", resourceCulture);
            }
        }
    }
}
