//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MezaTipsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MezaTipsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCalculator.Resources.MezaTipsResource", typeof(MezaTipsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar mežu neapklāta platība.
        /// </summary>
        internal static string ArMezuNeapklataPlatiba {
            get {
                return ResourceManager.GetString("ArMezuNeapklataPlatiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzīvnieku barošanas lauces.
        /// </summary>
        internal static string DzivniekuBarosanasLauces {
            get {
                return ResourceManager.GetString("DzivniekuBarosanasLauces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klajie sūnu purvi.
        /// </summary>
        internal static string KlajieSunuPurvi {
            get {
                return ResourceManager.GetString("KlajieSunuPurvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krūmāji.
        /// </summary>
        internal static string Krumaji {
            get {
                return ResourceManager.GetString("Krumaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neiežogotas lauksaimniecības platības.
        /// </summary>
        internal static string NeiezogotasLauksaimniecibasPlatibas {
            get {
                return ResourceManager.GetString("NeiezogotasLauksaimniecibasPlatibas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesaslēgušās E kultūras.
        /// </summary>
        internal static string NesaslegusasEKulturas {
            get {
                return ResourceManager.GetString("NesaslegusasEKulturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesaslēgušās P kultūras.
        /// </summary>
        internal static string NesaslegusasPKulturas {
            get {
                return ResourceManager.GetString("NesaslegusasPKulturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trases.
        /// </summary>
        internal static string Trases {
            get {
                return ResourceManager.GetString("Trases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virsāji.
        /// </summary>
        internal static string Virsaji {
            get {
                return ResourceManager.GetString("Virsaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zāļu pārejas un apauguši sūnu purvi.
        /// </summary>
        internal static string ZaluParejasUnApaugusiSunuPurvi {
            get {
                return ResourceManager.GetString("ZaluParejasUnApaugusiSunuPurvi", resourceCulture);
            }
        }
    }
}
